// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    401: typeof import('./src/components/error/401.vue')['default'];
    404: typeof import('./src/components/error/404.vue')['default'];
    AppLink: typeof import('./src/components/layout/side-bar/app-link.vue')['default'];
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default'];
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default'];
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default'];
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default'];
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default'];
    Layout: typeof import('./src/components/layout/index.vue')['default'];
    ParentView: typeof import('./src/components/layout/parent-view.vue')['default'];
    Redirect: typeof import('./src/components/layout/redirect/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SideBar: typeof import('./src/components/layout/side-bar/index.vue')['default'];
    SideBarLogo: typeof import('./src/components/layout/side-bar/side-bar-logo.vue')['default'];
    SideBarMenu: typeof import('./src/components/layout/side-bar/side-bar-menu.vue')['default'];
    SideBarMenuItem: typeof import('./src/components/layout/side-bar/side-bar-menu-item.vue')['default'];
    SvgIcon: typeof import('./src/components/common/svg-icon.vue')['default'];
  }
}
