// Generated by https://quicktype.io

export interface ServerMonitor {
  server: Server
  cpu: CPU
  cpu_load: CPULoad
  memory: Memory
  process: Process
  network: Network[]
}

export interface CPU {
  name: string
  arch: string
  processors: number
  frequency: number
  cores: string
  total_use: number
}

export interface CPULoad {
  one: number
  five: number
  fifteen: number
}

export interface Memory {
  totol_memory: number
  used_memory: number
  totol_swap: number
  used_swap: number
}

export interface Network {
  name: string
  received: number
  total_received: number
  transmitted: number
  total_transmitted: number
}

export interface Process {
  name: string
  used_memory: number
  used_virtual_memory: number
  cup_usage: number
  start_time: number
  run_time: number
  disk_usage: DiskUsage
}

export interface DiskUsage {
  read_bytes: number
  total_read_bytes: number
  written_bytes: number
  total_written_bytes: number
}

export interface Server {
  oper_sys_name: string
  host_name: string
  system_version: string
  system_kerne: string
}

export interface MonitorTable {
  rowOne?: string
  rowTwo?: any
  rowThree?: any
  rowFour?: any
  rowFive?: any
}
